name: Building

on: [push, workflow_dispatch]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: 20
      - name: Build test project
        run: |
          chmod +x gradlew
          ./gradlew nmpCopyBuildRelease --stacktrace
          tree
